USE freedb_VeterinariaAPP;
-- Define usuario master con cuenta admin con todas las funciones
CREATE TABLE TIPO_USUARIO(
    COD_TIPO_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION_TIPO_USUARIO VARCHAR(100),
    FECHA_INSERCION DATETIME DEFAULT CURRENT_TIMESTAMP, -- fecha por default
    UTENTE_INSERCION VARCHAR(8)
);
-- UTENTE INSERCION ES 71248074 (DNI YENIFER)
SELECT * FROM TIPO_USUARIO;
INSERT INTO TIPO_USUARIO (DESCRIPCION_TIPO_USUARIO, UTENTE_INSERCION)
VALUES
    ('Admin', '71248074'),
    ('Veterinario', '71248074'),
    ('Secretario', '71248074')
;
-- Creacion de la tabla de usuarios
USE freedb_VeterinariaAPP;
-- Define usuario master con cuenta admin con todas las funciones
CREATE TABLE USUARIOS(
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    IDENTIFICADOR VARCHAR(8),
    NOMBRES VARCHAR(200),
    APELLIDOS VARCHAR(200),
    COD_TIPO_USUARIO INT,
    FECHA_INSERCION DATETIME DEFAULT CURRENT_TIMESTAMP, -- fecha por default
    UTENTE_INSERCION VARCHAR(8)
);

SELECT * FROM USUARIOS U
LEFT JOIN TIPO_USUARIO TIP ON TIP.COD_TIPO_USUARIO = U.COD_TIPO_USUARIO;
SELECT * FROM USUARIO_CREDENCIALES;

INSERT INTO USUARIOS (IDENTIFICADOR, NOMBRES, APELLIDOS, COD_TIPO_USUARIO, UTENTE_INSERCION)
VALUES
    ('71248074','Yenifer', 'Escobar',1, '71248074')
;


USE freedb_VeterinariaAPP;
-- Define usuario master con cuenta admin con todas las funciones
CREATE TABLE USUARIO_CREDENCIALES(
    ID_CREDENCIALES INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT,
    EMAIL VARCHAR(200),
    PASSWORD VARCHAR(200),
    FECHA_INSERCION DATETIME DEFAULT CURRENT_TIMESTAMP, -- fecha por default
    UTENTE_INSERCION VARCHAR(8)
);
SELECT * FROM USUARIO_CREDENCIALES;

INSERT INTO USUARIO_CREDENCIALES (ID_USUARIO, EMAIL, PASSWORD, UTENTE_INSERCION)
VALUES
    (1,'yenifer_admin@master.com', 'adminpassword', '71248074')
;

-- Credenciales procedure 
DELIMITER //
CREATE PROCEDURE sp_obtener_credenciales(IN _email VARCHAR(200))
BEGIN
    SELECT 
        U.ID_USUARIO AS id,
        U.NOMBRES AS nombres,
        U.APELLIDOS AS apellidos,
        AUTH.EMAIL AS email,
        AUTH.PASSWORD AS password
    FROM USUARIOS U
    LEFT JOIN USUARIO_CREDENCIALES AUTH ON U.ID_USUARIO = AUTH.ID_USUARIO
    WHERE (_email IS NULL OR AUTH.EMAIL = CONCAT(_email));
END //
-- DROP PROCEDURE IF EXISTS sp_autenticador;
CALL sp_autenticador('yenifer_admin@master.com')

-- Autenticador procedure 
DELIMITER //
CREATE PROCEDURE sp_obtener_autenticador(IN _id INT)
BEGIN
    SELECT 
        U.ID_USUARIO AS id,
        U.IDENTIFICADOR AS autenticador,
        U.COD_TIPO_USUARIO AS cod_tipo_usuario,
        TIP.DESCRIPCION_TIPO_USUARIO AS desc_tipo_usuario
    FROM USUARIOS U
    LEFT JOIN TIPO_USUARIO TIP ON TIP.COD_TIPO_USUARIO = U.COD_TIPO_USUARIO
    WHERE (_id IS NULL OR U.ID_USUARIO = _id);
END //

-- Obtener Nombres
DELIMITER //
CREATE PROCEDURE sp_obtener_info_usuario(IN _identificador VARCHAR(60))
BEGIN
    SELECT 
        U.ID_USUARIO AS id,
        U.COD_TIPO_USUARIO AS cod_tipo_usuario,
        U.NOMBRES AS nombres,
        U.APELLIDOS AS apellidos,
        U.IDENTIFICADOR AS autenticador,
        TIP.DESCRIPCION_TIPO_USUARIO AS desc_tipo_usuario,
        AUTH.EMAIL AS email
    FROM USUARIOS U
    LEFT JOIN TIPO_USUARIO TIP ON TIP.COD_TIPO_USUARIO = U.COD_TIPO_USUARIO
    LEFT JOIN USUARIO_CREDENCIALES AUTH ON U.ID_USUARIO = AUTH.ID_USUARIO
    WHERE (_identificador IS NULL OR U.IDENTIFICADOR = _identificador);
END //
 -- DROP PROCEDURE IF EXISTS sp_obtener_info_usuario;
CALL sp_obtener_info_usuario('71248074');
-- TABLA PARA DEFINR FUNCIONES
CREATE TABLE TIPO_FUNCION(
    COD_TIPO_FUNCION INT AUTO_INCREMENT PRIMARY KEY,
    DESC_TIPO_FUNCION VARCHAR(200),
    PATH_IMAGEN VARCHAR(200),
    FECHA_INSERCION DATETIME DEFAULT CURRENT_TIMESTAMP, -- fecha por default
    UTENTE_INSERCION VARCHAR(8)
);

SELECT * FROM TIPO_FUNCION;
INSERT INTO TIPO_FUNCION (DESC_TIPO_FUNCION, UTENTE_INSERCION)
VALUES
	('Funciones', '71248074'), -- LA VIEW QUE CONTIENE TODAS LAS FUNCIONES
    ('Pacientes', '71248074'),
    ('Agendar Cita', '71248074'),
    ('Usuario', '71248074'),
    ('Veterinarios', '71248074'),
    ('Generar Informe', '71248074'),
    ('Historial Clinico', '71248074')
;
-- DEFINIR QUIEN TIENE ACCESO A NUESTRAS FUNCIONES
CREATE TABLE FUNCIONES_POR_TIPO_USUARIO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    COD_TIPO_USUARIO INT,
    COD_TIPO_FUNCION INT,
    FECHA_INSERCION DATETIME DEFAULT CURRENT_TIMESTAMP, -- fecha por default
    UTENTE_INSERCION VARCHAR(8)
);
SELECT * FROM FUNCIONES_POR_TIPO_USUARIO
-- ESTAMOS DEFINIENDO QUE EL TIPO USUARIO 'admin' POSEE TODAS LAS FUNCIONALIDADES
INSERT INTO FUNCIONES_POR_TIPO_USUARIO (COD_TIPO_USUARIO, COD_TIPO_FUNCION, UTENTE_INSERCION)
VALUES
    (1, 1, '71248074'),
    (1, 2, '71248074'),
    (1, 3, '71248074'),
    (1, 4, '71248074'),
    (1, 5, '71248074'),
    (1, 6, '71248074'),
    (1, 7, '71248074');
    
-- DEFINIR STORE PROCEDURE
-- Obtener Funciones por cod_tipo_usuario
DELIMITER //
CREATE PROCEDURE sp_obtener_info_usuario(IN _cod_tipo_usuario INT)
BEGIN
    SELECT 
		FUNC.ID as id,
        FUNC.COD_TIPO_USUARIO AS cod_tipo_usuario,
        TIP.DESCRIPCION_TIPO_USUARIO AS desc_tipo_usuario,
        TIP.DESC_TIPO_FUNCION AS desc_tipo_funcion,
        TIP.PATH_IMAGEN AS path_imagen,
        FUNC.COD_TIPO_FUNCION AS cod_tipo_funcion
    FROM FUNCIONES_POR_TIPO_USUARIO FUNC
    LEFT JOIN TIPO_USUARIO TIP ON TIP.COD_TIPO_USUARIO = FUNC.COD_TIPO_USUARIO
    LEFT JOIN TIPO_FUNCION TIP_FUNC ON TIP_FUNC.COD_TIPO_FUNCION = FUNC.COD_TIPO_FUNCION
    WHERE (_identificador IS NULL OR U.IDENTIFICADOR = _identificador);
END //
 -- DROP PROCEDURE IF EXISTS sp_obtener_info_usuario;

